export default [
  {
    year: 2014,
    month: 4,
    left: 14,
    text: [
      'ApDevice.cop is a startup company with the main focus on helping businesses make the most of their investment into JavaScript and Python applications.',
    ],
  },
  {
    year: 2014,
    month: 5,
    left: 22,
    img: ['/images/imagesWall/2.jpg'],
    text: ['龙哥发起“中欧校友经营管理群”'],
  },
  {
    year: 2015,
    month: 4,
    left: 12,
    img: ['/images/imagesWall/3.JPG', '/images/imagesWall/3-1.JPG', '/images/imagesWall/3-2.JPG'],
    text: [
      '五叶草成为“阿里云数加大数据”首家战略合作伙伴',
      '五叶草应阿里云数加邀请走进“云栖小镇”',
      '五叶草帮助打造阿里云数加大数据平台的线下生态',
    ],
  },
  {
    year: 2015,
    month: 5,
    left: 14,
    text: [
      '五叶草帮助阿里云数加举办首场亮相活动',
      '“阿里巴巴大数据踩坑之旅”专题讲座在“中欧国际工商学院CEIBS”校园举办',
      '五叶草帮助阿里云数加招募首批大数据合作伙伴',
    ],
  },
  {
    year: 2015,
    month: 8,
    left: 35,
    img: ['/images/imagesWall/5.jpg'],
    text: ['“杭州数空科技”成立于云栖小镇'],
  },
  {
    year: 2015,
    month: 9,
    left: 50,
    img: [
      '/images/imagesWall/6.jpg',
      '/images/imagesWall/6-2.jpg',
      '/images/imagesWall/6-3.jpg',
      '/images/imagesWall/6-4.jpg',
    ],
    text: [
      '“五叶草大数空间”开业',
      '浙江省长李强视察五叶草',
      '“阿里云数加大数据孵化培训基地”授牌',
      '五叶草成为中国首家大数据孵化器',
    ],
  },
  {
    year: 2015,
    month: 10,
    left: 55,
    img: '/images/imagesWall/3-1.jpg',
    text: [
      '五叶草参加首届“杭州云栖大会”',
      '五叶草推出“云栖下午茶”创客活动',
      '五叶草入选浙江科委主编的“创业是杯什么茶”一书',
    ],
  },
  {
    year: 2016.1,
    month: 1,
    left: 17,
    img: '/images/imagesWall/3-2.JPG',
    text: [
      '“阿里云数加”品牌在上海云栖大会正式推出',
      '龙哥发起并主持数加专场的“大数据奇葩说”',
      '龙哥发起并组织“阿里云数加业务交流钉钉群”',
    ],
  },
  {
    year: 2016.1,
    month: 2,
    left: 20,
    text: ['“银杏谷资本”天使轮入股数空科技'],
  },
  {
    year: 2016.1,
    month: 4,
    left: 45,
    text: ['数空科技投资“游蜗科技”VR旅游'],
  },
  {
    year: 2016.1,
    month: 5,
    left: 58,
    text: ['数空科技成为阿里云数加首批金牌大数据合作伙伴', '“有理数科技”在云栖小镇成立'],
  },
  {
    year: 2016.2,
    month: 8,
    left: 20,
    text: ['五叶草成为“浙江大学计算机实习就业基地“', '五叶草成为“中国美院孵化培训基地”'],
  },
  {
    year: 2016.2,
    month: 9,
    left: 30,
    img: ['/images/imagesWall/13.JPG'],
    text: [
      '“明优堂大数据”在云栖小镇成立',
      '五叶草负责运营的“阿里巴巴创新中心（南京江北新区基地）”开业',
    ],
  },
  {
    year: 2016.2,
    month: 10,
    left: 42,
    img: [
      '/images/imagesWall/14.JPG',
      '/images/imagesWall/14-2.JPG',
      '/images/imagesWall/14-3.JPG',
      '/images/imagesWall/14-4.JPG',
    ],
    text: ['五叶草参加第二届杭州云栖大会', '数空科技与阿里云数加联合发起“云栖大数据私董会”'],
  },
  {
    year: 2016.2,
    month: 11,
    left: 51,
    text: ['数空科技投资“博廉科技”云教育'],
  },
  {
    year: 2016.2,
    month: 12,
    left: 65,
    text: ['数空科技成为“阿里云DataV”数据可视化紧密合作伙伴'],
  },
  {
    year: 2017.1,
    month: 1,
    left: 25,
    text: [
      '数空科技为阿里巴巴王坚博士设计城市大脑视频（“浙江卫视思想跨年晚会”）',
      '数空科技投资“拼格艺术”',
    ],
  },
  {
    year: 2017.1,
    month: 2,
    left: 27,
    img: ['/images/imagesWall/18.JPG'],
    text: [
      '江苏省委书记李强视察阿里巴巴创新中心（南京江北新区基地）',
      '数空科技成为“阿里巴巴集团外包服务商“',
      '数空科技与“阿里云研究院”及“阿里巴巴创新中心”联合开发中国首个“双创大屏”',
    ],
  },
  {
    year: 2017.1,
    month: 3,
    left: 50,
    img: ['/images/imagesWall/19.JPG'],
    text: ['“双创大屏”在深圳、南京、成都云栖大会陆续发布'],
  },
  {
    year: 2017.1,
    month: 4,
    left: 55,
    img: ['/images/imagesWall/20.JPG'],
    text: [
      '五叶草“8第淘”创客集市在南京云栖大会发布',
      '数空科技成为“亿滋国际”（阿里云首家外资世界五百强企业客户）的大数据咨询服务商',
      '数空科技投资“犀语科技”',
    ],
  },
  {
    year: 2017.1,
    month: 5,
    left: 70,
    text: [
      '数空科技为“阿里大文娱”制作业务介绍可视化大屏（陈列于阿里巴巴集团西溪园区总部）',
      '数空科技成为“阿里巴巴集团采购供应商”',
    ],
  },
  {
    year: 2017.2,
    month: 9,
    left: 33,
    img: ['/images/imagesWall/22.JPG'],
    text: [
      '江苏省委副书记、常委副省长黄莉新视察阿里巴巴创新中心（南京江北新区基地）',
      '数空科技为“北京电力”开发网络安全监控（十九大献礼工程）',
      '数空科技开发“中国评画”APP',
    ],
  },
  {
    year: 2017.2,
    month: 10,
    left: 37,
    text: [
      '数空科技参加第三届杭州云栖大会',
      '数空科技设计云栖大会阿里云“工业大脑”数据可视化',
      '数空科技设计云栖大会阿里云“环境大脑”数据可视化',
    ],
  },
  {
    year: 2017.2,
    month: 11,
    left: 55,
    img: ['/images/imagesWall/24.JPG'],
    text: ['数空科技为“南京日报”开发算法模型和数据可视化'],
  },
  {
    year: 2017.2,
    month: 12,
    left: 65,
    text: [
      '数空科技为“云上贵州”开发IDC监控调度和数据可视化',
      '数空科技为“富士康“开发物联网环保云监控系统',
      '数空科技为“中冶集团”开发算法模型',
    ],
  },
  {
    year: 2018.1,
    month: 1,
    left: 36,
    text: ['数空科技参加“浦东城市大脑建设”', '数空科技为“红星美凯龙”提供3D新媒体设计'],
  },
  {
    year: 2018.1,
    month: 2,
    left: 50,
    text: [
      '五叶草成为“2050志愿发起机构”',
      '有理数设计“２０５０官网”',
      '龙哥被王坚博士指定为“2050　CTO”',
    ],
  },
  {
    year: 2018.1,
    month: 5,
    left: 60,
    img: ['/images/imagesWall/28.JPG'],
    text: [
      '五叶草参加首届“２０５０”',
      '龙哥发起“2050数据之美青年团聚”',
      '龙哥发起“2050数据之美新生论坛”',
    ],
  },
  {
    year: 2018.2,
    month: 7,
    left: 40,
    img: ['/images/imagesWall/29.JPG'],
    text: ['数空科技为阿里高德开发“高德打车”平台'],
  },
  {
    year: 2018.2,
    month: 8,
    left: 45,
    img: ['/images/imagesWall/30.JPG', '/images/imagesWall/30-2.JPG'],
    text: ['“上海数空科技”成立于上海浦东新区“张江科学城”（“英特尔机器人创新中心”）'],
  },
  {
    year: 2018.2,
    month: 9,
    left: 60,
    text: ['数空科技为“数字广西”提供“东盟博览会”可视化'],
  },
  {
    year: 2018.2,
    month: 11,
    left: 66,
    text: ['数空科技作为核心开发团队参加建设的“浦东城市大脑”接受习近平总书记检阅'],
  },
  {
    year: 2019,
    month: 1,
    left: 45,
    text: ['数空科技为“浦东环保局”提供大AI服务', '数空科技为“浦东城管执法局”提供大AI服务'],
  },
  {
    year: 2019,
    month: 1,
    left: 50,
    img: [
      '/images/imagesWall/34.JPG',
      '/images/imagesWall/30-2.JPG',
      '/images/imagesWall/30-3.JPG',
      '/images/imagesWall/30-4.JPG',
    ],
    text: ['数空科技为“浦东大数据中心”提供大AI服务'],
  },
  {
    year: 2019,
    month: 3,
    left: 65,
    text: ['数空科技为宁波“国家海洋博物馆”提供“一带一路”数据可视化'],
  },
  {
    year: 2019,
    month: 4,
    left: 70,
    text: [
      '数空科技参加第二届“2050”',
      '龙哥发起2050“城市之美”青年团聚、新生论坛、探索展区',
      '数空科技为“黄河科技学院”提供大AI服务',
    ],
  },
];
